### ISSUE TITLE
Automatic market closing

### ISSUE THREAD

**Issue by tbirrell** [Stock-Watch-App/Stockwatch#58]
We want to let a cron job take care of closing the market each week. This should look like a new column in the `seasons` table to record an hour, and a cron job that will run every Thursday at that hour EST and close the market. Theoretically, we can also use this value to update the FAQ and the banner automatically each season.

**Comment by jroski** [comment]
Is the market closed by calling end() on the market controller?

**Comment by tbirrell** [comment]
No, when I originally wrote the code I thought there would be market closing actions. But it turned out to not be needed and I forgot about that code. The market is closed by setting the season to `closed` in the DB. The only code that does that is [in the SeasonManager in Nova](https://github.com/Stock-Watch-App/Stockwatch/blob/49c56d7dd86f68f839579f9bdc533a21e9751a65/nova-components/SeasonManager/resources/js/components/Tool.vue#L42).

**Comment by tbirrell** [comment]
For the cron job, it can be as simple as `Season::current()->update(['status' => 'closed']);`

**Comment by tbirrell** [comment]
Ah, I lied. `end()` is for the end of the market. Final leaderboard and all that.
