### ISSUE TITLE
Incorporate percentage ranking in leaderboard and profile

### ISSUE THREAD

**Issue by tbirrell** [Stock-Watch-App/Stockwatch#60]

**Comment by jroski** [comment]
I think I can tackle this one. In terms of percentages, do you think it should only list certain tiers (e.g. 1/5/10/25/50) or every percentage (e.g. 1/2/3/4/5...)

**Comment by langermank** [comment]
Hey Jeff! I'm the other half of Stock Watch handling just front-end things, primarily markup and CSS. If you want to grab more front-end related JS tickets that's great! I'd like for us to collaborate on anything front-end that requires styling or new markup, so if you want to start a branch I can style whatever data you surface. 

I'll get clarity from Taran on what he wants for tiers and let you know!

Also, Timothy and I will go through our backlog and mark things with help wanted so you know what to grab from. But feel free to ask if you see something that looks like fun!

**Comment by jroski** [comment]
That sounds great, thanks Katie!

**Comment by langermank** [comment]
@jroski Got confirmation from Taran that he would prefer tiers. 1/5/10/25/50 looks good, and we should also add 75.

**Comment by jroski** [comment]
I've started a branch on my fork that provides a new "rank_percentage" attribute on the leaderboard model. Let me know if you want me to add that to the frontend, or if you'd rather handle it yourself!

**Comment by tbirrell** [comment]
How heavy is this computationally? I'm worried about running 6000 duplicate queries to find the total every time the leaderboard loads (which is already our heaviest query, hands down). Would it be possible to move the calculation forward into a computed Vue property or method? We can grab the total from the array length and then offload some of the computational load to the client.

**Comment by jroski** [comment]
Totally valid point! I wrapped the query in cache call so it won't be executed more than once every 10 seconds. It caches based on the season and week, so it shouldn't call more than once per load of the BB22 leaderboard (maybe 2-3 times since it loads slow right now.)

I opted to put the logic on the backend since it looks like the total might not be available client side once issue #53 is handled and the data is paginated?

**Comment by langermank** [comment]
I went ahead and made a feature branch off master: https://github.com/Stock-Watch-App/Stockwatch/tree/leaderboard-percent-stats

When you and Timothy are happy with the backend implementation, I think you should be able to merge it into my branch so I can surface the data to the leaderboard.

**Comment by tbirrell** [comment]
I think this is fine for now. If it proves to still be too heavy with the caching, we can just shift it backwards to the Leaderboard generation and save the value to the DB instead of calculating it on the fly. But that won't affect the front end, so we should be fine in that department.

**Comment by langermank** [comment]
Not sure if I'm totally following, but does this implementation not store to the DB? If that's the case, does that mean we can't display this stat as historical data? We have a profile page in progress that will allow you to view data week over week, so just curious how this stat fits into that model (if it does at all).

**Comment by tbirrell** [comment]
We can because the data is saved as a static set. Someone is always Rank #X of Y. Right now we would be calculating it each time, but the result won't change.

**Comment by jroski** [comment]
The only negative in that scenario is that it would run a query for every week. In that case I will adjust to store the percent in the DB!

**Comment by jroski** [comment]
@tbirrell Where are leaderboards generated from?

**Comment by langermank** [comment]
Any strong opinions on visuals? I think the tooltip is best, otherwise it feels really cluttered. 

1 inline: 
![image](https://user-images.githubusercontent.com/18661030/92314010-112a1d80-efa0-11ea-9030-d97f9882ce3f.png)

2 stacked: 
![image](https://user-images.githubusercontent.com/18661030/92314124-b5f92a80-efa1-11ea-96fc-2ccd1e3bf8aa.png)

3 tooltip: 
![image](https://user-images.githubusercontent.com/18661030/92314072-ed1b0c00-efa0-11ea-9017-540278349a00.png)

**Comment by jroski** [comment]
I agree

**Comment by tbirrell** [comment]
I agree tooltip is best.

**Comment by langermank** [comment]
Great! Here's the PR with the tooltip https://github.com/Stock-Watch-App/Stockwatch/pull/68

@jroski I noticed the values returned are exact instead of in tiers. Could you help make that adjustment?
